steps:
  - name: "gcr.io/cloud-builders/gcloud"
    script: |
      gcloud run deploy cloudrunservice --image us-docker.pkg.dev/cloudrun/container/hello --region asia-east1 --platform managed --allow-unauthenticated
