steps:
  - name: "node"
    entrypoint: "npm"
    args: ["test"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-node-app", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-node-app"]

images:
  - "gcr.io/$PROJECT_ID/my-node-app"
