swagger: "2.0"
info:
  title: app-engine-cloud-function-cloud-run
  description: Sample API on API Gateway with an App Engine, Cloud Function and Cloud Run backends
  version: 1.0.2
schemes:
  - https
produces:
  - application/json
paths:
  /app-engine:
    get:
      summary: App Engine
      operationId: app-engine
      x-google-backend:
        address: https://api-dot-fast-campus-serverless.et.r.appspot.com
      responses:
        "200":
          description: A successful response
          schema:
            type: string

  /cloud-function:
    get:
      summary: Cloud Function
      operationId: cloud-function
      x-google-backend:
        address: https://asia-southeast2-fast-campus-serverless.cloudfunctions.net/nodejs-http-function
      responses:
        "200":
          description: A successful response from Cloud Function
          schema:
            type: string

  /cloud-run:
    get:
      summary: Cloud Run
      operationId: cloud-run
      x-google-backend:
        address: https://fastify-cloudrun-702660660622.asia-southeast2.run.app
      responses:
        "200":
          description: A successful response from Cloud Function
          schema:
            type: string
